### ISSUE TITLE
Documentation for `createStore` is incorrect

### ISSUE THREAD

**Issue by bloomdido** [microsoft/redux-dynamic-modules#101]
As pointed out in https://github.com/microsoft/redux-dynamic-modules/issues/100, the signature of `createStore` was changed for v5.0.0, but the documentation has not been updated to reflect this change.

**Comment by abettadapur** [comment]
Thanks for pointing that out, I will update the page today

**Comment by abettadapur** [comment]
Fixed by 6d4a9e
