### ISSUE TITLE
When i call any connected component in the Dynamic module will break app

### ISSUE THREAD

**Issue by ashokkumarsand** [microsoft/redux-dynamic-modules#102]
I have below code 
`<DynamicModuleLoader modules={[getCommonModule()]}>
        <AppHeader />
        <ErrorBoundary>
          <UserProvider
            redirectLoginURL={`${process.env.REACT_APP_ACCESS_SERVER}login.jsp`}
            redirectLogoutURL={`${process.env.REACT_APP_ACCESS_SERVER}logout.jsp`}
          >
            <Suspense fallback={<AppLoader />}>
              <Router>
                <Route path={"/"} component={AppFrame} />
              </Router>
            </Suspense>
          </UserProvider>
        </ErrorBoundary>
      </DynamicModuleLoader>`

**AppHeader** is redux component, When I add any other connected component face below error. 

Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.

I didn't used hooks. **AppHeader** is class component. All required dependencies are latest expect react-router and react-router-dom.

**Comment by ashokkumarsand** [comment]
This is an issue with the React hooks. Are we having any version of the dynamic module without hooks

**Comment by abettadapur** [comment]
We do not use hooks in this library. 
How are you consuming the library? It sounds like this might be a configuration issue on your end, as we do not bundle React or React-Redux with the library (or at least we shouldn't)

**Comment by abettadapur** [comment]
Confirmed that we do not bundle React anywhere in this library, so this sounds like a configuration issue on your end.

**Comment by ashokkumarsand** [comment]
@abettadapur There are two scenarios. one with all update version of all required libs and component library is also a part of the mono repo from where I am exporting connected component and modules. In that scenario, I am getting hooks error. 

Another scenario is that when I downgrade the react-redux version to 6.0.1. in that case, I am getting a below-mentioned error. 

_**Could not find "store" in the context of "Connect(Frame)". Either wrap the root component in a <Provider>, or pass a custom React context provider to <Provider> and the corresponding React context consumer to Connect(Frame) in connect options.**_

Note: component libraries a web lib are part of mono repo

**Comment by ashokkumarsand** [comment]
The second scenario is invalid. That is a bundler issue.

**Comment by kg-currenxie** [comment]
> The second scenario is invalid. That is a bundler issue.

did you fix it? i'm getting **Could not find "store" in the context** as well.
