### ISSUE TITLE
Question: default sagas and modules

### ISSUE THREAD

**Issue by vincentljn** [microsoft/redux-dynamic-modules#105]
Hi,

In order to achieve a clean startup of my app, I initialize `redux-dynamic-modules` like this : 

```
const sagaExtension = getSagaExtension()
const store = createStore({
	extensions: [sagaExtension],
})
sagaExtension.middleware[0].run(sharedSagas)
store.addModule(rootModule)
```

`sharedSagas` are a bunch of default sagas used by each module across the app
`rootModule` is the default module that performs the startup flow

Everything works but I found it pretty verbose.
I've seen we can pass initial modules in the `createStore` function but I need the `sharedSagas` to be registered first and I can't run `sharedSagas` before creating the store.

Is there a shortcut for such a workflow?

**Comment by abettadapur** [comment]
A module need not contain reducers, so you could create a module that just contains your sagas and add it before your root module

**Comment by abettadapur** [comment]
Could you elaborate more on your use case? Why do those sagas need to be mounted first?

**Comment by vincentljn** [comment]
I mean I can't run `sharedSagas` before the redux-saga extension has been registered on redux.

To clarify the use case:
`sharedSagas` contains common sagas like api fetching or storage access. They will be used by modules across the app.
`rootModule` is the 'app' module which basically executes the startup flow (the startup saga calls default apis to retrieve the mandatory assets for the app to run (config, i18n, ...). This saga uses `sharedSagas`.

Does that make any sense?

**Comment by codeocelot** [comment]
@vincentljn, if I understand you correctly, then I think the issue here is really controlling the execution of `rootModule` sagas to come *after* `sharedSagas` has been started.  

Is `sharedSagas` an argument-less 'background' worker shared between your modules?  If so, then why not `fork` or `spawn` it within the rootModule saga?  (I'm assuming the rootModule will always be mounted).  Then it'll always be running during the app.

**Comment by vincentljn** [comment]
Thanks @codeocelot but everything is currently working.
I was just wondering if `redux-dynamic-modules` has a built-in api cleaner than adding the `rootModule` to the store after running `sharedSagas` in `sagaExtension`, something like :

```
const sagaExtension = getSagaExtension(sharedSagas) // like default sagas
const store = createStore({
	extensions: [sagaExtension],
	defaultModules: [rootModule]
})
```

compared to my current implementation :

```
const sagaExtension = getSagaExtension()
const store = createStore({
	extensions: [sagaExtension],
})
sagaExtension.middleware[0].run(sharedSagas)
store.addModule(rootModule)
```

**Comment by abettadapur** [comment]
No, we do not. The suggested way to run sagas (and everything, really) with this library is through a module
