### ISSUE TITLE
Can you config with react-router with multi pages?

### ISSUE THREAD

**Issue by xuanlongvts** [microsoft/redux-dynamic-modules#114]
Now, you have put all pages in one file https://github.com/microsoft/redux-dynamic-modules/blob/master/packages/widgets-example/src/App.js

But, with a big application, there are many pages, so we have to use react-router to config router for entries app. 

Can you demo with an application with react-router-dom?

Thank you!

**Comment by sinack** [comment]
I pushed a simple demo using `redux-dynamic-modules` with `react-router-dom` and `connected-react-router`.

Please use this as a reference.
[demo](https://github.com/sinack/redux-dynamic-modules-sample)

**Comment by navneet-g** [comment]
Thanks @sinack   ...  Pretty cool  👍
