### ISSUE TITLE
Provide Readmes NPM

### ISSUE THREAD

**Issue by Lusito** [microsoft/redux-dynamic-modules#135]
The npm pages all say something like "Unable to find a readme for redux-dynamic-modules@5.2.0", which looks a bit concerning when browsing potential packages:
https://www.npmjs.com/package/redux-dynamic-modules

I think there should at least be a minimal readme per package included, which gives a short overview and points to the github page and/or homepage for more details.

I really think this project deserves more attention and the missing readme might be something that makes people turn away.

**Comment by abettadapur** [comment]
Thanks for the suggestion!
