### ISSUE TITLE
Support for keeping state mounted

### ISSUE THREAD

**Issue by MmtBkn** [microsoft/redux-dynamic-modules#154]
Hello,

We have a case where we'd like to keep state after It's initialization for caching purposes. 

Current Behaviour;
DynamicModuleLoader loads the state when mounted, and removes it when unmounted

Ask;
DynamicModuleLoader loads the state when mounted, and won't remove the state when unmounted based off a flag, so the existing state could be reused without initialization. 

Thank you.

**Comment by fostyfost** [comment]
@MmtBkn hello. Try 'retained: true' for your module.
