### ISSUE TITLE
PENDING action is gone from sagas

### ISSUE THREAD

**Issue by per0w** [microsoft/redux-dynamic-modules#169]
Hello. Please help. I faced with problem when i move my project to module with redux-dynamic-modules and redux-dynamic-modules-saga. Actions from sagas starts to work differently. Now actions not including PENDING prefix. Maybe someone came across this?

redux-promise-middleware - stopped working yet I don't know why

![image](https://user-images.githubusercontent.com/20511462/115146872-864aee80-a069-11eb-9696-eef00a8d1ce8.png)

**Comment by fostyfost** [comment]
Please provide a codesandbox demo

**Comment by per0w** [comment]
> Please provide a codesandbox demo

https://github.com/microsoft/redux-dynamic-modules/pull/172

**Comment by fostyfost** [comment]
It's not a demo 🙃

**Comment by per0w** [comment]
> It's not a demo 🙃

Fix problem it's the best demo. ;) In fact, it was just that external middleware such as redux-promise and etc. were not included in the extension for sagas.

**Comment by fostyfost** [comment]
You can pass middlewares for modules, isn't it enough?

**Comment by per0w** [comment]
> You can pass middlewares for modules, isn't it enough?

nope, b/c inside to saga extension they are not passed
