### ISSUE TITLE
Fix the observable extension

### ISSUE THREAD

**Issue by abettadapur** [microsoft/redux-dynamic-modules#17]
The original idea for the observable extension did not work correctly
We need to figure out exactly how RxJS works and come up with a better option for dynamically loading Epics

**Comment by leoyli** [comment]
Here is one resource found from in the `redux-observable` repo:
https://github.com/redux-observable/redux-observable/blob/master/docs/recipes/AddingNewEpicsAsynchronously.md

I might take a look to see how I can make it work.

**Comment by navneet-g** [comment]
That will be great ... thanks @leoyli .

**Comment by ilionic** [comment]
Using this approach https://github.com/redux-observable/redux-observable/blob/master/docs/recipes/AddingNewEpicsAsynchronously.md
in custom redux way but would be great to have extension.

**Comment by shinvey** [comment]
Now [EpicManager](https://github.com/shinvey/redux-dynamic-modules-observable/blob/master/src/EpicManager.ts) is implemented and it makes [observable extension](https://github.com/shinvey/redux-dynamic-modules-observable) work properly. The [key idea](https://github.com/redux-observable/redux-observable/blob/master/docs/recipes/HotModuleReplacement.md) is using [Subject](https://www.learnrxjs.io/subjects/subject.html) and [switchMap](https://www.learnrxjs.io/operators/transformation/switchmap.html) in RxJS. I can't wait to share the code with you guys, even though I haven't finished all unit tests yet...

Many thanks to redux-dynamic-modules project. So we can practice code splitting of redux + redux-observable. I will make a PR after our refactor task has been finished in the following months.

**Comment by dyaa** [comment]
@shinvey I tested the package and it's working as expected, Maybe time to merge back?

Thanks a lot for your effort

**Comment by ahrnee** [comment]
Great! I was just looking for a way to leverage redux-observable with redux-dynamic-modules. Any idea when this update will make it into a release?

**Comment by abettadapur** [comment]
I will cut a release today. I think I have to work with Microsoft to create a new package, as I no longer work there, but let me see what I can do

**Comment by abettadapur** [comment]
Turns out it was easy, published 5.2.0 to NPM.
Please let me know if you have any issues

**Comment by ahrnee** [comment]
> Turns out it was easy, published 5.2.0 to NPM.
> Please let me know if you have any issues

Thanks @abettadapur!
