### ISSUE TITLE
Support React-Redux V6

### ISSUE THREAD

**Issue by winklerp** [Microsoft/redux-dynamic-modules#27]
React-Redux v6 will use React's ( new ) context api which is not compatible with the legacy context API. By accessing store from context ( reference ) it causes the app to break when it tries to dynamic load modules.

"Could not load store from React context" - Error is thrown in DynamicModuleLoader.

As @timdoor has described in its breaking changes:

Passing store as a prop to a connected component is no longer supported. Instead, you may pass a custom context={MyContext} prop to both <Provider> and <ConnectedComponent>. You may also pass {context : MyContext} as an option to connect.

**Comment by abettadapur** [comment]
@winklerp Thanks I'll take a look

**Comment by abettadapur** [comment]
@winklerp Here, I think we can use the ReactReduxContext.Consumer that is exposed, and get the same behavior

**Comment by winklerp** [comment]
Hi, it works with ReactReduxContext.Consumer but since React-Redux 6 supports custom context I think we should pass the context into dynamic module loader and not rely hard coded on ReactReduxContext.

**Comment by winklerp** [comment]
Hi, ReactReduxContext.Consumer works. But since React-Redux 6 supports custom context I think we should pass the context into DynamicModuleLoader and not only rely hard coded on ReactReduxContext.

See release notes of react redux 6.0-beta:

• Passing store as a prop to a connected component is no longer supported. Instead, you may pass a custom context={MyContext} prop to both <Provider> and <ConnectedComponent>. You may also pass {context : MyContext} as an option to connect.

With this it is possible to have several stores in different contexts. So this is why I think passing the context to module loader is necessary. By the way: if we pass a property named store, react redux throws an exception :). Only passing the context works.

**Comment by cschleiden** [comment]
It's released now.

**Comment by abdurahmanus** [comment]
Is it ok that I get undefined when I try to access dynamic modules's state ("myModule") when I wrap Lazy component with connect function and use it inside DynamicModuleLoader component? Is't it supposed to have "myModule" to be loaded?

https://codesandbox.io/s/7200w810n6

**Comment by abettadapur** [comment]
@navneet-g Could you chime in here? I am able to reproduce the problem reported above, but I am not sure why

**Comment by navneet-g** [comment]
@abdurahmanus myModule is NOT loaded async in the sandbox above. Redux prohibits returning undefined from the state, I see that someValueReducer is not initializing the state if it is undefined.

Please let me know if I am missing anything.

**Comment by navneet-g** [comment]
@abdurahmanus  This is really interesting ... I spent sometime in debugging but did not reach a conclusion, so far it is pointing in direction that it is outside scope of redux dynamic modules and something related to react and react-redux. For example see below screenshot, the _this2.setState actually calls mapStateToProps twice first with old state that does not have myModule state set and immediately after correct state.

![image](https://user-images.githubusercontent.com/13487927/51420437-cfd4c800-1b46-11e9-96fb-1388582a249e.png)

**Comment by abdurahmanus** [comment]
@navneet-g it seems like this behavior was changed somewhere in between v5.1.1 and 6.0.0 of react-redux.
the same example with react-redux v5.1.1 works different way (no undefined value)
https://codesandbox.io/s/xj6l40kjqw
The question is what should be considered as correct behavior? If (while loading process) some module could be undefined it should have nullable type in *AwareState interface (if ts using) and should be checked for undefined value in mapStateToProps or anywere else.

**Comment by navneet-g** [comment]
If this is a behavior change in react-redux, please open an issue there, we can take it forward then depending upon if they make changes.

**Comment by abdurahmanus** [comment]
I've also noticed that todo-example uses react-redux@6 and it's broken now
![image](https://user-images.githubusercontent.com/7404552/51688203-2b023100-2005-11e9-8b37-37a7a6851a00.png)

**Comment by navneet-g** [comment]
I did further debugging and opened following issue in react-redux repo
https://github.com/reduxjs/react-redux/issues/1194

**Comment by navneet-g** [comment]
This seems like due to a known change in react-redux with their support to new context API.
https://github.com/reduxjs/react-redux/issues/1126

We need to update DynamicModuleLoader as follows https://codesandbox.io/s/pwmm8r3110
I probably won't have time, if someone wants to make change and send the PR, it would be awesome.
