### ISSUE TITLE
redux-dynamic-modules-saga: get all runned sagas

### ISSUE THREAD

**Issue by Stoope** [Microsoft/redux-dynamic-modules#31]
I use ssr and need to wait for all actions to end(all data has fetched). To ensure all actions have end I send END action and wait for done promise (https://medium.com/@victor36max/using-redux-saga-with-next-js-2b5d5add1ec6)
```javascript 
const runnedSaga = sagaMiddleware.run(...);
...
store.dispatch(END);
runnedSaga.done.then(...);
```
How can I get all runned sagas to something like `Promise.all(...runnedSagas.done).then(...)`?

**Comment by navneet-g** [comment]
Thanks for your question @Stoope. I may be missing something so please pardon my ignorance.

The saga extension only helps in starting the saga when the module is loaded and removing the saga when the module is unloaded.

Are you asking that you want to wait for all sagas to be done across all modules, or is it just in the scope of a single module?

If it is for a single module then you can create a root saga that forks/calls other sagas and then can wait for them to finish.

We can also setup a quick call to go over your scenario in detail and discuss solutions.

**Comment by Stoope** [comment]
@navneet-g Thank you for reply.
I want to wait for all sagas to be done across all modules.
To do it I need to get this variable (tasks, https://github.com/Microsoft/redux-dynamic-modules/blob/6a72b2e82603b148b601e7d575a42c1caf29b070/packages/redux-dynamic-modules-saga/src/SagaManager.ts#L10 ) from outer code and do something like
```javascript
Promise.all(tasks.keys.map(key => sagasTasks.get(key).done)).then(...)
```
I tried and it works for me.

**Comment by navneet-g** [comment]
This translates to the scenario when all modules are unloaded or the store is disposed, right?
An alternate way to do this is by creating your own IExtension and giving it to the store.  Then you can either listen to onModuleAdded, onModuleRemoved and do refcounting, or you can execute your code in dispose of the extension. In my opinion it is a cleaner approach then waiting for all tasks to be done, as more modules get loaded unloaded all the time.

**Comment by navneet-g** [comment]
@Stoope does this help? Please let me know if you have any questions.

**Comment by navneet-g** [comment]
@Stoope I am closing the issue, please feel free to open a new one or Reactivate if you have more questions on this.

**Comment by Stoope** [comment]
@bslinger take a look at my fork https://github.com/Stoope/redux-dynamic-modules

**Comment by lanyusan** [comment]
@navneet-g 

Can you expose `tasks` in SagaManager.ts as @Stoope did? I found I need this too but don't want to use a fork.

Thanks.
