### ISSUE TITLE
Read initial state from server

### ISSUE THREAD

**Issue by Stoope** [Microsoft/redux-dynamic-modules#32]
I want to pass preloaded state from server
```javascript
createStore(window.__PRELOADED_STATE__, [], [sagaMiddleware])
```
 (https://redux.js.org/recipes/serverrendering#client-js)
Problem is initial state passed to createStore overwrites by initial state from each dynamically loaded reducer. How can I apply preloaded state to them?

**Comment by navneet-g** [comment]
@Stoope  We don't overwrite any state intentionally, I will try it out and see if I can get a repro.

**Comment by Stoope** [comment]
@navneet-g Have made playground https://codesandbox.io/s/k917m5ppjv. If you remove `defaultModule` from `createStore` app works as expected.

**Comment by navneet-g** [comment]
Awesome ... thanks for doing it @Stoope  ... I will take a look tonight or over the weekend.

**Comment by navneet-g** [comment]
@Stoope  I took a look, this is happening as the keys in initialState are ignored by combinedReducer, as the defaultModule does not contain any reducers for those keys. If the defaultModule can contain the 

Notice line 163 onwards in following file in redux code.
https://github.com/reduxjs/redux/blob/3f93d6bb21fd104263bc83da87bd2e113e82bd9f/src/combineReducers.js

I have modified the playground to illustrate it
https://codesandbox.io/s/xj49x173kz

Please let me know if you have any question.

**Comment by Stoope** [comment]
@navneet-g Thanks, I see... This is a problem since I don't know about other reducers at initial stage, they will be added later with react-loadable. Best solution is to read `window.__PRELOADED_STATE__.somereducer` state in each module's reducer, right?

**Comment by navneet-g** [comment]
Yes ... That is an alternative, I don't know though, when does the library overwrites the state in window object.

**Comment by navneet-g** [comment]
Closing as hopefully the above answered the question, please reopen if you still need help with this.
