### ISSUE TITLE
Feature request: Passing store to have it configured

### ISSUE THREAD

**Issue by raRaRa** [Microsoft/redux-dynamic-modules#41]
Hi,

I have a feature request that might be useful for people who don't want to change how `createStore` or `configureStore` is used. I found it a bit confusing that I had to import `createStore` from this lib instead of Redux, and the params were in different order, and TBH I never got it to work with enhancers and redux-first-router.

How about this: We create the store as we've always done it before, but we'd simply pass the store to the library. And the library would simply add the reducer injection and other things it needs to make it a dynamic store.

So for example: `const dynamicStore = reduxDynamicConfigure(store)` or something.

What do you think?

**Comment by navneet-g** [comment]
Thanks @raRaRa for filing the issue. Please repro steps for redux-first-router. I will also take a look and see if we can create a high order function as you suggested, but that might take some time.

**Comment by raRaRa** [comment]
Thanks for the quick response @navneet-g.

Currently `redux-first-router` requires you to connect routes, like so:
```
    const {
        reducer: rfrReducer,
        middleware: rfrMiddleware,
        enhancer: rfrEnhancer,
        thunk: rfrThunk,
    } = connectRoutes(history, routesMap, options)
```

This gives me a reducer, middleware and enhancer for `redux-first-router`.

What confuses me is whether or not I need to create a module for all reducers, e.g. am I required to create a module for the `redux-first-router` reducer, or can I simply pass the reducer to `createStore`?

My use case is that I have plenty of reducers that need to load on startup with the app, such as a user reducer. But at the same time I also want to load some reducers dynamically. So it's a bit annoying if I have to create a module for the startup reducers.

Thanks!

**Comment by navneet-g** [comment]
You can create a single module with all the reducers, middlewares at the startup. e.g.
```
const startupModule = {
  "id":"startup-module",
   reducerMap: {
      rfr: frfReducer,
      user: userReducer
  },
  middlewares: [rfrMiddleware]
}
```

**Comment by raRaRa** [comment]
Clever, thanks! One last question. RFR (Redux-first-router) has an enhancer, which is then composed to the middleware. How would this case be handled?

```
const middleware = applyMiddleware(...middlewares)
const enhancers = compose(rfrEnhancer, middleware)
```

**Comment by navneet-g** [comment]
Second parameter to createStore function is enhancers, you can pass it there.

**Comment by navneet-g** [comment]
Closing the issue as I have not heard any followup questions.

**Comment by raRaRa** [comment]
Hey again. I had to take a pause on this task but I'm still trying to figure this out.

This is what I've got so far:

```
    // Configure Redux-First-Router (RFR), which gives back a RFR reducer, middleware and enhancer.
    const {
        reducer: rfrReducer,
        middleware: rfrMiddleware,
        enhancer: rfrEnhancer,
    } = connectRoutes(history, routesMap, options)

    // Here are my middlewares
    const middlewares = [
        userMiddleware,
        rfrMiddleware,
        thunk,
    ]

   // I want to have everything in my startup module to begin with
    const startupModule = {
        id: 'startup-module',
        reducerMap: {
            user,
            payments,
            location: rfrReducer,
        },
        middlewares: [...middlewares],
    }

    const store = createStore(
        preloadedState,
        [rfrEnhancer],
        [],
        startupModule,
    )
```
The solution above makes something crash inside Redux-First-Router, like something is not composed or configured properly. From the RFR documentations I need to compose the middlewares with the rfrEnhancer, like so:

```
    const middleware = applyMiddleware(...middlewares)
    const enhancers = compose(rfrEnhancer, middleware)
```

Should I pass enhancers instead of rfrEnhancer to the second parameter in `createStore`? It all feels a bit strange since I've already passed the middlewares to the startup module.

Thank you!

**Comment by raRaRa** [comment]
I believe the issue is that the RFR enhancer expects rfrReducer's default state to be loaded into the store. But that doesn't happen until after `@@Internal/ModuleManager/ModuleAdded`.

**Comment by raRaRa** [comment]
Is it possible to add reducers to the internal createStore?
