### ISSUE TITLE
Example of parameterized module

### ISSUE THREAD

**Issue by abdurahmanus** [microsoft/redux-dynamic-modules#45]
How do you think, does this example make sense?
https://codesandbox.io/s/rw92p548np

I was trying to use the fact that we can pass params to factory function which returns module

**Comment by navneet-g** [comment]
Thanks @abdurahmanus , in this example the module is not prrameterized. You have a factory function that returns a new module based on the parameters. 
What exactly are you asking about? ```redux-dynamic-modules``` does not care how the module object is created.

**Comment by abettadapur** [comment]
@abdurahmanus Any updates on this?

**Comment by abdurahmanus** [comment]
You can definitely close this issue
