### ISSUE TITLE
Typescript Recipes

### ISSUE THREAD

**Issue by abettadapur** [Microsoft/redux-dynamic-modules#46]
Add some recipes for typescript, including concepts such as *AwareState

**Comment by navneet-g** [comment]
We have a typescript example, do you plan to further update it?
https://github.com/Microsoft/redux-dynamic-modules/tree/master/packages/typescript-example

**Comment by abettadapur** [comment]
We need documentation on the website regarding what patterns are good to use

**Comment by abdurahmanus** [comment]
I mentioned some problems with typings in this issue: https://github.com/Microsoft/redux-dynamic-modules/issues/36
Imagine I have 2 modules:
module1:
![image](https://user-images.githubusercontent.com/7404552/51461648-afd41d00-1d6f-11e9-9900-48082eccb809.png)
![image](https://user-images.githubusercontent.com/7404552/51461695-ced2af00-1d6f-11e9-864a-35d86c711131.png)
and module2 which depends on module1:
![image](https://user-images.githubusercontent.com/7404552/51461732-ec077d80-1d6f-11e9-90aa-c32d1bf6ebee.png)
Module2AwareState extends Module1AwareState (as in official typescript-example)
![image](https://user-images.githubusercontent.com/7404552/51461812-2b35ce80-1d70-11e9-9703-0d84974105ee.png)
and I get this error from ts:
![image](https://user-images.githubusercontent.com/7404552/51461946-6cc67980-1d70-11e9-9364-12ad2ead1bcf.png)
I've also tried to use IModuleTuple interface as a return type of getModule2s function, but in this case I've lost ts benefits
![image](https://user-images.githubusercontent.com/7404552/51462458-b19ee000-1d71-11e9-9bbb-5344442c7971.png)

**Comment by abdurahmanus** [comment]
of course getModule2s from example above should return module with id "module2"

**Comment by abdurahmanus** [comment]
also I could create temp valiable with type IModule<Module2AwareState>, but reducerMap still wants from me reducer for module1 key.
![image](https://user-images.githubusercontent.com/7404552/51463271-d5fbbc00-1d73-11e9-8228-6b2e4113fbd1.png)

**Comment by abdurahmanus** [comment]
another unclear point. DynamicModuleLoader's modules prop type is array of IModuleTuple:
![image](https://user-images.githubusercontent.com/7404552/51466081-6f2dd100-1d7a-11e9-9b6e-c964a5903868.png)
Does it mean what I aways should wrap getModuleXXX in array when I pass it to DynamicModuleLoader component even if it already returns array of modules like this?
![image](https://user-images.githubusercontent.com/7404552/51466250-ca5fc380-1d7a-11e9-9373-40ea2063a183.png)
Or maybe something wrong with typings?

**Comment by navneet-g** [comment]
@abettadapur can you respond to the IModuleTuple part of the question?
Regarding the typing issue with reducer, recently we also experience it and follow this pattern, we should update the example to cover this.

```
interface IModule1AwareState {
key1: string;
}

interface IModule2OwnState {
   key2: string;
}

interface IModule2AwareState extends IModule2OwnState, IModule1AwareState {
   
}

const _module2: IModule<IModule2OwnState> = {
...
}

// We just use implicit typing for getModule2 method.
function getModule2() {
return [
getModule1(),
_module2
]
}
```

**Comment by danrfg** [comment]
I've been having trouble with typings: The IModuleTuple problem above and using getState() to return a typed object rather than <any>. I'm considering creating a getState<IMyModuleState>() function that can return the strongly typed module state... is something like this in the works at all?

**Comment by danrfg** [comment]
The confusion I have is in the examples. There is `createStore<State>` that returns an `IModuleStore<State>` which I guess helps you ensure modules will conform whatever State is, which I suppose would be the module schema e.g. id, reducerMap, initialActions etc.

Then there's the IModule<State> where State is whatever the reducer for that module returns e.g. IModule<IUserState>. 

The problem comes from store.getState() to grab a particular module for testing. And as they're all typed as `any` in the DynamicModuleLoader, is there any need to strongly type any IModule? 
I feel like I'm missing something with regards to implementation.

**Comment by danrfg** [comment]
Btw I wrapped createStore in my own createStore function that has a `getModuleById<T>(moduleId:string)` function that returns a typed module for testing, other than that I can't see how I could easily integrate this with the rest of the sdk.
