### ISSUE TITLE
Remove react / react-redux from redux-dynamic-modules

### ISSUE THREAD

**Issue by danrfg** [Microsoft/redux-dynamic-modules#49]
Is there any reason, other than convenience, that react and react-redux are in the redux-dynamic-modules package.json? I'm currently experimenting with using this as a headless redux layer that can be ported to different presentation layers e.g. React, React Native, possibly angular-redux. 

It'd be great if this library didn't contain those dependencies.

**Comment by navneet-g** [comment]
We take a dependency on Provider from react-redux. I am not familiar with how angular-redux, react native connects to the store. Can you shed some light and we can talk about how to abstract it.

**Comment by danrfg** [comment]
It only seems you need react-redux / react for the DynamicModuleLoader, is that correct? Could that not be moved out to its own package like thunk or saga, so there is no hard react dependency in redux-dynamic-modules? Then you could create headless redux modules that can be tested in isolation that you could use as a basis for React and ReactNative apps. As for Angular it might be more difficult to integrate, still experimenting with that.

**Comment by abettadapur** [comment]
@danrfg I am working on this now

**Comment by ryanf5** [comment]
Hi, thank you for the excellent library. It seems like redux-dynamic-modules-saga still depends on redux-dynamic-modules instead of redux-dynamic-modules-core. Do you mind if I submit a PR that updates the reference?

**Comment by abettadapur** [comment]
Sorry about that. Please do and I'll approve it
