### ISSUE TITLE
Hot reload slowdown

### ISSUE THREAD

**Issue by vincentljn** [microsoft/redux-dynamic-modules#51]
I'm experiencing a hot reloading slowdown after implementing redux-dynamic-modules and redux-dynamic-modules-saga (v3.2.0) in my medium-size application.
Is it something you are aware of?

**Comment by navneet-g** [comment]
Can you take a profiler trace and share what is slowing it down?

**Comment by abettadapur** [comment]
@vincentljn Were you able to capture a profiler trace here?

**Comment by vincentljn** [comment]
Not yet but I'll take some time next week to tackle that point.
If I guess right you don't experienced this issue, correct ?

**Comment by abettadapur** [comment]
Correct, we have not seen anything like this. We are happy to take a look at the trace when you get it though and figure out what is wrong

**Comment by vincentljn** [comment]
Here's a profile trace.
Nothing happens during 15s, excepts garbage collects. Then the hot reloading process starts and takes 15 more seconds before the page is reloaded.
I can't see anything slowing the reloading down. Do you ?
[Profile-20190218T181726.txt](https://github.com/Microsoft/redux-dynamic-modules/files/2876791/Profile-20190218T181726.txt)

**Comment by vincentljn** [comment]
After further investigations, I found a lead to explain the slowdown:
I use to reference my service functions in a `index.js` and call them like : 
```index.js
export * from './doingSomethingServices'
```
```
import {doSomething} from 'services'
```
instead of:
```
import {doSomething} from 'services/doingSomethingServices'
```
If I remove the index file and call the functions directly from the final js file, hot reload works as usual.
Am I clear? Is that make sense?

**Comment by abettadapur** [comment]
I think that this is not related to this library, but instead something in your hot reload configuration (based on your above comment)

**Comment by intelcoder** [comment]
I thought redux-dynamic-modules not supporting hot reloading yet
