### ISSUE TITLE
Support for ImmutableJS reducer state

### ISSUE THREAD

**Issue by codeocelot** [microsoft/redux-dynamic-modules#52]
I'd love to use ImmutableJS with this project however, this project is hardwired to use redux's own `combineReducers`.  Are the maintainers interested in refactoring the app to allow for less dependency on the underlying Redux state implementation?

**Comment by abettadapur** [comment]
I am not too familiar with ImmutableJS, could you help explain why combineReducers is incompatible with the library?

**Comment by abettadapur** [comment]
@navneet-g , maybe we can use the extension model like we did with sagas to add a new reducermanager that would support this behavior?

We could also add other reducer behaviors that have been requested

**Comment by abettadapur** [comment]
@navneet-g @codeocelot  I'll find some time this weekend to look at this

**Comment by luskin** [comment]
@abettadapur Looking forward to `immutable` support over here, thanks!

**Comment by luskin** [comment]
@abettadapur have you had a chance to take a look at this?

**Comment by bflamand** [comment]
Any progress with support for immutablejs?
Support for immutablejs is the only thing preventing us from using this library...

**Comment by abettadapur** [comment]
Sorry for the long delay on this, and thank you for being patient!

I just put out a PR #90 which allows you to pass a custom combineReducers function. From what I see in redux-immutable, this should solve the issue

@navneet-g Could you review?

**Comment by abettadapur** [comment]
@luskin @codeocelot Please try 5.0.0-alpha.0

Again, sorry for the delay on this

**Comment by abettadapur** [comment]
Closing, this has been released

**Comment by victorparamo** [comment]
Hi! I'm writing just to ask if someone have had some issues removing keys using immutable.
