### ISSUE TITLE
mapStateToProps not initialize state

### ISSUE THREAD

**Issue by HASSANDL** [Microsoft/redux-dynamic-modules#54]
I use redux-dynamic-modules/todo-example after run below error.
```
src/containers/root/FilterLink.js:6
TypeError: Cannot read property 'visibilityFilter' of undefined

const mapStateToProps = (state, ownProps) => ({
   active: ownProps.filter === state.root.visibilityFilter,
});
```

I use redux-dynamic-modules@^3.3.1, in my project too same error.

**Comment by abettadapur** [comment]
Which version of `react-redux` are you using?

**Comment by abettadapur** [comment]
@HASSANDL We are aware of an issue with `react-redux@6.0` which we have yet to resolve. Stay tuned

**Comment by HASSANDL** [comment]
@abettadapur Very very thanks. downgrade to reacr-redux@5.1.1, problem solved.

**Comment by abettadapur** [comment]
Closing this for now, as it is tracked by #27
