### ISSUE TITLE
Dynamic Module Loader props are loaded on second render

### ISSUE THREAD

**Issue by winstonjz** [Microsoft/redux-dynamic-modules#60]
Hey! 
I love the project. Been looking for something like this to replace react-boilerplate's injectReducer and injectSaga. 

I noticed that the DynamicModuleLoader renders its children on the first load
I forked the widgets example in this codesandbox: https://codesandbox.io/s/k9jo0kyzw5 and added a log statement in the `mapStateToProps` in `src/widgets/hacker-news/`. The log statement prints 
![screen shot 2019-02-18 at 9 29 31 pm](https://user-images.githubusercontent.com/20022500/52992144-5984e900-33c4-11e9-96b9-a9b62d6cbd15.png)

Is there a way to prevent the rendering of the child component until the modules are all loaded from DynamicModuleLoader? I use PropTypes in my project and a required prop will force me to make default values for my selectors as the state will not exist until the second render.

**Comment by navneet-g** [comment]
Are you using react-redux 6.0? I have a pull request to fix that.

**Comment by abettadapur** [comment]
@winstonjz For now, it is recommended to use `react-redux@5.x`. As Navneet mentioned, #59 will fix your issue

**Comment by navneet-g** [comment]
This should be fixed with #59
