### ISSUE TITLE
Can each instance of the component has its standalone state in the redux store?

### ISSUE THREAD

**Issue by nikechanhk** [Microsoft/redux-dynamic-modules#63]
For example, in the Widgets example, the hacker-news has its unique id and the store key to the reducer. However, if I declare more than one instance of hacker-news, all instance will point to the same reducer and than all content of each hacker-news will be the same.

If I change the code in this way.
```
export function getHackerNewsModule(id) {
    const keyName = 'hackerNews' + id;
    const map = {};
    map[keyName] = hackerNewsReducer;

    return {
        // Unique id of the module
        id: keyName,
        // Maps the Store key to the reducer
        reducerMap: map,
        // Optional: Any actions to dispatch when the module is loaded
        initialActions: [fetchStories()],
        // Optional: Any actions to dispatch when the module is unloaded
        finalActions: [],
    };
}
```
each instance of hacker-news will have its standalone reducer in redux store and each instance can present own content.
Is this the correct way for my purpose?

**Comment by anilanar** [comment]
This is what we also do plus a little more magic. Every action has metadata that includes its “component id” so that the reducer can update the correct state slice. So it’s a reducer factory; as in `hackerNewsReducer(id)`.

**Comment by navneet-g** [comment]
Yes it is fine to do it this way.
