### ISSUE TITLE
Pass options to devtools

### ISSUE THREAD

**Issue by anilanar** [microsoft/redux-dynamic-modules#65]
Although it is convenient to include devtools integration in this library, there's a fair question to ask here: is it this library's responsibility to do it? If it's done for technical reasons, I think we need a way to pass options to the devtools' compose function.

Particularly action blacklisting, state sanitization, max-age are invaluable for large apps.

In addition, different apps have different needs (e.g. using devtools in production etc.). There are infinitely many possible ways to configure devtools. What if `createStore` took a `compose` function as a parameter?

Another alternative (as seen in other issues/questions submitted) is to have an additional API that exports enhancers/middlewares for dynamic module management and let users seeking more freedom use `createStore` from `redux`.

If you would like to go with the first option (adding compose param to `createStore`), I can make a PR. I suggest that `createStore`’s first argument is made an options object in that case e.g. `createStore<...>(options: { compose, initialState, enchancersEtc }, ...modules)`. I’m typing from mobile so this is not a type signature :smile:

It seems it’d be better if this were done after https://github.com/Microsoft/redux-dynamic-modules/pull/55 is merged. Nevertheless this will be a breaking change.

**Comment by anilanar** [comment]
For now, I have a fork that takes `compose` function as argument.

**Comment by navneet-g** [comment]
@anilanar  Please feel free to send a PR.

**Comment by navneet-g** [comment]
@anilanar  what if we create an option to createStore that tells it to not compose with devtools, and you can pass devtools as an enhancer in createStore?

**Comment by anilanar** [comment]
@navneet-g Devtools' compose function iterates all enhancers and generates an `instanceId` for each intermediate store created by enhancers:

https://github.com/zalmoxisus/redux-devtools-extension/blob/master/src/browser/extension/inject/pageScript.js#L383-L400

I don't understand why it needs to do that though. So `createStore({}, reduxDevtoolsCompose([/* enhancers */]))` would make devtools miss enhancers added by `redux-dynamic-modules`' own `createStore`.

**Comment by dbartholomae** [comment]
Any way I can help here? This is a major hindrance for us using this package now :-/

**Comment by anilanar** [comment]
I don’t see a way to make this a non-breaking change.

If maintainers are fine with a breaking change, and if they propose the new API, I can make a PR. Otherwise I don’t want to waste time on bikeshedding.

**Comment by navneet-g** [comment]
@abettadapur  what if we take a compose function as input? @dbartholomae @anilanar  will that help?

**Comment by dbartholomae** [comment]
Taking a function sounds great! And if enhancers is a function instead of a middleware, dev-tools are not included by default. If this approach is fine, I could try to write a PR.

**Comment by anilanar** [comment]
I propose:

```
// The following plus 8 overloads for `DeepPartial<union of module states>`

interface StoreOptions<S> {
  initialState: S,
  enhancers?: StoreEnhancer[],
  extensions?: IExtension[],
  compose?: typeof reduxCompose,
  modules: IModule<any>[],
}

export declare function createStore<S>(options: StoreOptions<S>): IModuleStore<S>;
```

**Comment by anilanar** [comment]
I'm working on this now.

**Comment by dbartholomae** [comment]
Any news on the PR? Looking forward to this!

**Comment by anilanar** [comment]
Sorry I’ve been on a long vacation with no access to computers, will handle this when I’m back.
On 23. Aug 2019, 04:40 +0300, Daniel Bartholomae <notifications@github.com>, wrote:

Any news on the PR? Looking forward to this!
