### ISSUE TITLE
Browser freezes with redux dev tools open

### ISSUE THREAD

**Issue by luskin** [Microsoft/redux-dynamic-modules#73]
When using `redux-dynamic-modules` my browser freezes and crashes whenever I try and open the redux debugger. If I remove dynamic module loader and re-implement using standard redux setup everything works fine. Anybody else having this issue? Renders this otherwise useful package useless to us.

**Comment by abettadapur** [comment]
@luskin Sorry to hear that! I have not experienced the problem you are referring to unfortunately :(

Could you provide a minimal repro? You can use this as a starter https://codesandbox.io/s/8kx2jr7762

**Comment by luskin** [comment]
@abettadapur Thanks! I tried to replicate on codesandbox this weekend and couldn't get the problem to replicate. I'm going to keep working on narrowing it down and see if I can pinpoint it to a specific part of the package, thanks.

In the meantime if anyone else has experienced this issue and can shed some light it would be much appreciated!

**Comment by luskin** [comment]
After upgrading to react-redux `7.0.0-beta.0` this issue has since resolve, closing as this is no longer an issue for me.
