### ISSUE TITLE
Possible bug when used with React-Redux v7

### ISSUE THREAD

**Issue by markerikson** [microsoft/redux-dynamic-modules#76]
`redux-dynamic-modules-react` currently has this chunk of code:

https://github.com/Microsoft/redux-dynamic-modules/blob/8d9bbbbb037abeae2b3f4f62345668097c0f8015/packages/redux-dynamic-modules-react/src/DynamicModuleLoader.tsx#L141-L150

This was related to a bug that popped up in React-Redux v7 beta 0, at https://github.com/reduxjs/react-redux/issues/1219 .

Looking at the code further, I can see that you're rendering a `<ReactReduxContext.Provider>` with your own value.  By doing that, you're actually going to completely override the context value from React-Redux itself.  That context value normally looks like `{store, subscription]` in v7.  Based on your code, the `subscription` value will be lost, and nested connected components will not be updated in the correct sequence, and will not take advantage of React's batched updates.

I'd suggest changing this chunk to render both a `<ReactReduxContext.Consumer>` and a `<ReactReduxContext.Provider>`, pass down a context value that looks like `{store, storeState, subscription}`, and memoize producing that value so that it doesn't keep changing on every render (to avoid unnecessary context-caused updates).

**Comment by abettadapur** [comment]
Thanks for pointing this out to us!

This is a common class of bug I have seen using hooks now,  maybe I should write a PSA on it :)

**Comment by navneet-g** [comment]
Thanks @markerikson  for reporting the issue and  @abettadapur for fixing it. @abettadapur is the issue still open as we are waiting for a new release, or something else?

**Comment by abettadapur** [comment]
We have been using 4.0.0-alpha.1 for awhile now with React Redux 7. No
issues that I can tell. We should publish 4.0.0

**Comment by navneet-g** [comment]
Thanks @abettadapur  ... I assume we don't need to port anything to 3.*. I will publish 4.0.0 today.
