### ISSUE TITLE
Integration with Redux Beacon

### ISSUE THREAD

**Issue by dbartholomae** [microsoft/redux-dynamic-modules#95]
In case someone is interested: I have written an extension for Redux Dynamic Modules that allows to connect to Redux Beacon.
Redux Beacon is a library that allows transform Redux actions into analytic events with different providers like Google Analytics, Segment or Matomo. With help of this extension events do not have to be defined in one central location but can be defined for each module individually.

The extension can be found [here](https://github.com/dbartholomae/redux-dynamic-modules-beacon).

The corresponding ticket in the other repo can be found here:
https://github.com/rangle/redux-beacon/issues/341

**Comment by navneet-g** [comment]
This is really awesome, thanks for the contribution @dbartholomae .
